"""Add created_at to chat history

Revision ID: cec30a96999c
Revises: 3ce2ba19e6c7
Create Date: 2026-08-08 21:25:30.193221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec30a96999c'
down_revision: Union[str, Sequence[str], None] = '3ce2ba19e6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'chat_history',
    sa.Column(
        'created_at',
        sa.DateTime(),
        nullable=False,
        server_default=sa.text('CURRENT_TIMESTAMP')
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'created_at')
    # ### end Alembic commands ###
